Fixes opts

diff --git a/bin/hs-wp-create b/bin/hs-wp-create
--- a/bin/hs-wp-create
+++ b/bin/hs-wp-create
@@ -101,7 +101,7 @@ if [ $domain = 0 ]
 fi
 devDomain="$answer"
 
-if [ "$prefix" -ne "0" ]
+if [ $prefix != 0 ]
     then
         project_prefix="$prefix"
 fi
@@ -191,16 +191,6 @@ echo "Editing hosts file (You might be asked to provide your user's password for
 # edit hosts file
 echo -e "\n$vagrantIp $devDomain" | sudo tee -a $hosts_file
 
-echo "Editing Homestead.yaml file ..."
-# edit Homestead.yaml
-if [ -e "$homesteadFolder/Homestead.yaml" ]
-    then
-        file="$homesteadFolder/Homestead.yaml"
-    else
-        echo "Homestead's folder path was incorrect, Homestead.yaml not found in folder"
-        exit 1
-fi
-
 siteFolderLength=${#siteFolder}
 endLength=$[$siteFolderLength-7]
 sFolder="$siteFolder"
@@ -241,6 +231,16 @@ if [ "$noproject" = "0" ]
             unzip -o $P
             rm $P
         done)
+fi
+
+echo "Editing Homestead.yaml file ..."
+# edit Homestead.yaml
+if [ -e "$homesteadFolder/Homestead.yaml" ]
+    then
+        file="$homesteadFolder/Homestead.yaml"
+    else
+        echo "Homestead's folder path was incorrect, Homestead.yaml not found in folder"
+        exit 1
 fi
 
 awk -v from="folders:.*$" -v to="folders:\n    - map: $sFolder\n      to: /home/vagrant/$siteFolderWithoutHomeDir" '{gsub(from,to,$0); print $0}' $file > ${file}.tmp
