Adds defaults.ini and explains more in the Readme

diff --git a/bin/hs-wp-create b/bin/hs-wp-create
--- a/bin/hs-wp-create
+++ b/bin/hs-wp-create
@@ -1,22 +1,34 @@
 #!/bin/bash
+
+#
+# You can find defaults.ini with all the defaults from the scripts root dir
+#
+
 echo
 echo "Simple way to add nginx Wordpress Projects to Homestead"
 echo
 
-# Open-source Wordpress plugins
-# You can get this url from Wordpress's site
-wordpressPlugins="
-advanced-custom-fields.4.4.11.zip
-wordpress-seo.5.1.zip
-w3-total-cache.0.9.5.4.zip
-"
-
-defaultWordpressRepo="https://github.com/phzfi/wordpress-boilerplate"
-
-
-# Script itself
-function lowercase {
-    lowercased=`echo $1 | tr '[A-Z]' '[a-z]'`
+# Functions
+function cfg_parser
+{
+    ini="$(<$1)"                # read the file
+    ini="${ini//[/\[}"          # escape [
+    ini="${ini//]/\]}"          # escape ]
+    IFS=$'\n' && ini=( ${ini} ) # convert to line-array
+    ini=( ${ini[*]//;*/} )      # remove comments with ;
+    ini=( ${ini[*]/\    =/=} )  # remove tabs before =
+    ini=( ${ini[*]/=\   /=} )   # remove tabs be =
+    ini=( ${ini[*]/\ =\ /=} )   # remove anything with a space around =
+    ini=( ${ini[*]/#\\[/\}$'\n'cfg.section.} ) # set section prefix
+    ini=( ${ini[*]/%\\]/ \(} )    # convert text2function (1)
+    ini=( ${ini[*]/=/=\( } )    # convert item to array
+    ini=( ${ini[*]/%/ \)} )     # close array parenthesis
+    ini=( ${ini[*]/%\\ \)/ \\} ) # the multiline trick
+    ini=( ${ini[*]/%\( \)/\(\) \{} ) # convert text2function (2)
+    ini=( ${ini[*]/%\} \)/\}} ) # remove extra parenthesis
+    ini[0]="" # remove first element
+    ini[${#ini[*]} + 1]='}'    # add the last brace
+    eval "$(echo "${ini[*]}")" # eval the result
 }
 
 function random-string()
@@ -24,6 +36,10 @@ function random-string()
     cat /dev/urandom | env LC_CTYPE=C tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1
 }
 
+# Load defaults
+source <(grep = $(dirname "$0")"/../defaults.ini")
+
+# Script itself
 if [ -z "$1" ]
     then
         echo -n "Please enter site's name (for example project1.app): "
@@ -38,7 +54,7 @@ if [ -z "$2" ]
     then
         echo
         echo "Path to site's public directory on host machine. "
-        echo "Path will be prefixed with your $HOME/workspace/wordpress/"
+        echo "Path will be prefixed with your $project_prefix"
         echo -n "Folder to use: "
         read answer
     else
@@ -46,20 +62,19 @@ if [ -z "$2" ]
 fi
 
 vSiteFolder="/home/vagrant/$answer"
-siteFolder="$HOME/workspace/wordpress/$answer"
-siteFolderFromHomeDir="workspace/wordpress/$answer"
+siteFolder="$project_prefix/$answer"
 siteFolderWithoutHomeDir="$answer"
 
 if [ -z "$3" ]
     then
         echo
         echo "Homestead's IP address "
-        echo -n "(leave blank for 192.168.10.10): "
+        echo -n "(leave blank for $homestead_ip): "
         read answer
 
         if [ -z "$answer" ]
             then
-                answer="192.168.10.10"
+                answer="$homestead_ip"
         fi
 
     else
@@ -71,30 +86,30 @@ vagrantIp="$answer"
 if [ -z "$4" ]
     then
         echo "Homestead's folder path "
-        echo -n "(leave blank for $HOME/Homestead): "
+        echo -n "(leave blank for $homestead_folder): "
         read answer
 
         if [ -z "$answer" ]
             then
-                answer="$HOME/Homestead"
+                answer=$homestead_folder
         fi
 
     else
         answer="$4"
 fi
 
-vagrantPath="$answer"
+homesteadFolder="$answer"
 
 # create folder if project doesn't exist
 if [ -z "$5" ]
     then
         echo "Insert the projects Git repo "
-        echo -n "(leave blank for default: $defaultWordpressRepo): "
+        echo -n "(leave blank for default: $wordpress_repo): "
         read answer
 
         if [ -z "$answer" ]
             then
-                answer=$defaultWordpressRepo
+                answer=$wordpress_repo
         fi
     else
         answer="$5"
@@ -111,15 +126,16 @@ ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no vagrant@127.0.0.
 
 echo "Editing hosts file (You might be asked to provide your user's password for host machine)..."
 # edit hosts file
-echo -e "\n$vagrantIp $devDomain" | sudo tee -a /etc/hosts
+echo -e "\n$vagrantIp $devDomain" | sudo tee -a $hosts_file
 
 echo "Editing Homestead.yaml file ..."
 # edit Homestead.yaml
-if [ -e "$HOME/Homestead/Homestead.yaml" ]
+if [ -e "$homesteadFolder/Homestead.yaml" ]
     then
-        file="$HOME/Homestead/Homestead.yaml"
+        file="$homesteadFolder/Homestead.yaml"
     else
-        file="$vagrantPath/Homestead.yaml"
+        echo "Homestead's folder path was incorrect, Homestead.yaml not found in folder"
+        exit 1
 fi
 
 siteFolderLength=${#siteFolder}
@@ -155,17 +171,11 @@ echo "Installing default plugins..."
 (cd $sFolder/web/app/plugins/
 
 # Go through the plugins and get them to the correct folder
-for P in $wordpressPlugins; do
+for P in $wordpress_plugins; do
 	curl -sS https://downloads.wordpress.org/plugin/$P > $P
 	unzip -o $P
 	rm $P
 done)
-
-echo "Running Composer install"
-(cd $sFolder && composer install)
-
-echo "Running Yarn install"
-(cd $sFolder && yarn install)
 
 awk -v from="folders:.*$" -v to="folders:\n    - map: $sFolder\n      to: /home/vagrant/$siteFolderWithoutHomeDir" '{gsub(from,to,$0); print $0}' $file > ${file}.tmp
 awk -v from="sites:.*$" -v to="sites:\n    - map: $devDomain\n      to: $vSiteFolder/web" '{gsub(from,to,$0); print $0}' ${file}.tmp > ${file}2.tmp
@@ -177,27 +187,31 @@ rm -f ${file}2.tmp
 mv ${file}3.tmp $file
 
 echo "Restarting your Homestead VM..."
-(cd $vagrantPath && vagrant destroy --force && vagrant up)
+(cd $homesteadFolder && vagrant destroy --force && vagrant up)
+
+echo "Running Yarn install & Composer install inside Vagrant"
+echo "If ssh asks for password, its usually 'vagrant'"
+(cd $homesteadFolder && vagrant ssh -- -t 'cd /home/vagrant/$siteFolderWithoutHomeDir && yarn install && composer install')
 
 read -r -p "Want to create a local Jenkins Job? [y/N] " response
 case "$response" in
     [yY][eE][sS]|[yY])
         echo "Insert the local Jenkins Server url "
-        echo -n "(leave blank for default: http://localhost:8080): "
+        echo -n "(leave blank for default: $local_jenkins_url): "
         read jenkinsServerUrl
 
         if [ -z "$jenkinsServerUrl" ]
             then
-                jenkinsServerUrl="http://localhost:8080"
+                jenkinsServerUrl=$local_jenkins_default_url
         fi
 
         echo "Insert the local Jenkins Server username "
-        echo -n "(leave blank for default: jenkins): "
+        echo -n "(leave blank for default: $local_jenkins_username): "
         read jenkinsServerUsername
 
         if [ -z "$jenkinsServerUsername" ]
             then
-                jenkinsServerUsername="jenkins"
+                jenkinsServerUsername=$local_jenkins_username
         fi
 
         scriptDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
@@ -224,12 +238,12 @@ case "$response" in
         read jenkinsServerUrl
 
         echo "Insert the deployment Jenkins Server username "
-        echo -n "(leave blank for default: jenkins): "
+        echo -n "(leave blank for default: $deploy_jenkins_username): "
         read jenkinsServerUsername
 
         if [ -z "$jenkinsServerUsername" ]
             then
-                jenkinsServerUsername="jenkins"
+                jenkinsServerUsername=$deploy_jenkins_username
         fi
 
         scriptDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
